name: todolist
description: "TodoList com Flappy Bird integrado"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Background.png
    - assets/IsNotDuolingo.png
    - assets/bird_crop.png
    - assets/pipe_top_crop.png
    - assets/pipe_bot_crop.png
    - assets/Poste_alto.png
    - assets/Poste_baixo.png
    - assets/Poste_medio.png